language: ruby

pre:
 - gem update bundler

cache: bundler

rvm:
 - 2.0
 - 2.1
 - 2.2.3
 - ruby-head
 - jruby
 - jruby-head

env:
  - JRUBY_OPTS="--2.0"

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
